server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://81.68.128.229:3306/wxedu?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: ZZ123zz!

mybatis:
  type-aliases-package: com.nemt.nemtj.model
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  mapUnderscoreToCamelCase: true